<?php
/**
 * Created by PhpStorm.
 * User: youdone-dev
 * Date: 2019/2/20
 * Time: 9:31
 */

namespace app\admin\controller;


use think\Db;

class Feedback extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        parent::assignRouteInfo();
    }

    //列表页
    public function feedbackList()
    {

        return $this->fetch();
    }

    //获取列表内容
    public function getFeedbackList()
    {
        $searchContent = request()->param('search');

        $cond = [];
        if ($searchContent) {
            $cond['content|contact'] = ['like', "%$searchContent%"];
        } else {
            $cond = 1;
        }

        $list = Db::name('feedback')->where($cond)->order('createdatetime desc')->paginate(10);

        $data = ['table' => $list->items(), 'page' => $list->render()];
        return json(['code' => 'SUCCESS', 'data' => $data]);
    }
}