<?php
namespace app\admin\controller;

class Index extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        parent::assignRouteInfo();
    }

    public function index()
    {
        return $this->fetch();
    }
}
