<?php
/**
 * Created by PhpStorm.
 * User: youdone-dev
 * Date: 2019/2/13
 * Time: 11:09
 */

namespace app\admin\controller;


class Vote extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        parent::assignRouteInfo();
    }

    //投票活动列表
    public function voteList()
    {

        return $this->fetch();
    }

    //选项列表
    public function optionList()
    {

    }

    //选项数据
    public function getOptionData()
    {

    }

    //新增投票活动
    public function publishView()
    {
        return $this->fetch();
    }

    //投票活动明细
    public function detailView()
    {

    }

    //编辑投票活动
    public function editView()
    {

    }

    //结束投票活动
    public function closeVote()
    {

    }

    //保存投票活动
    public function saveVote()
    {

    }

    //删除投票活动
    public function deleteVote()
    {

    }

    //投票统计数据
    public function voteStats()
    {

    }

    public function fileUpload()
    {
        // 获取表单上传文件 例如上传了001.jpg
        $file = request()->file('file');

        // 移动到框架应用根目录/public/uploads/ 目录下
        if($file){
            $info = $file->validate(['size'=>1024*1024, 'ext'=>'gif,jpg,jpeg,bmp,png'])->move(ROOT_PATH . 'public' . DS . 'uploads');
            if($info){

                return json(['code' => 'SUCCESS', 'name' => $info->getSaveName()]);
            }else{
                // 上传失败获取错误信息
                return json(['code' => 'ERROR', 'msg' => $info->getError()]);
            }
        }
    }
}